import { JobApplication, PipelineVelocityData } from '@/types';

const today = new Date();
const daysAgo = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
};

export const MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-001',
    company: 'Stripe',
    role: 'Senior Frontend Engineer',
    location: 'San Francisco, CA (Remote)',
    salary: '$180k – $220k',
    status: 'interview_scheduled',
    appliedDate: daysAgo(18),
    lastActivity: daysAgo(1),
    requiresAction: true,
    schedulingLink: 'https://calendly.com/stripe-eng',
    logo: 'S',
    source: 'LinkedIn',
    tags: ['React', 'TypeScript', 'Remote'],
  },
  {
    id: 'app-002',
    company: 'Vercel',
    role: 'Developer Experience Engineer',
    location: 'Remote',
    salary: '$160k – $200k',
    status: 'shortlisted',
    appliedDate: daysAgo(20),
    lastActivity: daysAgo(3),
    requiresAction: false,
    logo: '▲',
    source: 'Company Website',
    tags: ['Next.js', 'DevEx', 'Open Source'],
  },
  {
    id: 'app-003',
    company: 'Figma',
    role: 'Staff Software Engineer',
    location: 'New York, NY',
    salary: '$200k – $250k',
    status: 'under_review',
    appliedDate: daysAgo(12),
    lastActivity: daysAgo(2),
    requiresAction: false,
    logo: '🎨',
    source: 'Referral',
    tags: ['Canvas API', 'WebGL', 'Performance'],
  },
  {
    id: 'app-004',
    company: 'Linear',
    role: 'Full Stack Engineer',
    location: 'Remote',
    salary: '$150k – $190k',
    status: 'applied',
    appliedDate: daysAgo(5),
    lastActivity: daysAgo(5),
    requiresAction: false,
    logo: '📐',
    source: 'AngelList',
    tags: ['React', 'Node.js', 'GraphQL'],
  },
  {
    id: 'app-005',
    company: 'Notion',
    role: 'Product Engineer',
    location: 'San Francisco, CA',
    salary: '$170k – $210k',
    status: 'rejected',
    appliedDate: daysAgo(30),
    lastActivity: daysAgo(8),
    requiresAction: false,
    logo: '📝',
    source: 'Indeed',
    tags: ['React', 'Collaboration', 'EdTech'],
  },
  {
    id: 'app-006',
    company: 'Datadog',
    role: 'Frontend Platform Engineer',
    location: 'New York, NY (Hybrid)',
    salary: '$175k – $215k',
    status: 'interview_scheduled',
    appliedDate: daysAgo(25),
    lastActivity: daysAgo(1),
    requiresAction: true,
    schedulingLink: 'https://calendly.com/datadog-talent',
    logo: '🐕',
    source: 'Greenhouse',
    tags: ['Observability', 'TypeScript', 'Hybrid'],
  },
  {
    id: 'app-007',
    company: 'Shopify',
    role: 'Senior React Developer',
    location: 'Ottawa, Canada (Remote)',
    salary: '$140k – $175k',
    status: 'shortlisted',
    appliedDate: daysAgo(22),
    lastActivity: daysAgo(4),
    requiresAction: false,
    logo: '🛍️',
    source: 'Lever',
    tags: ['React', 'Ruby', 'E-commerce'],
  },
  {
    id: 'app-008',
    company: 'Cloudflare',
    role: 'Edge Computing Engineer',
    location: 'Remote',
    salary: '$160k – $200k',
    status: 'under_review',
    appliedDate: daysAgo(9),
    lastActivity: daysAgo(3),
    requiresAction: false,
    logo: '☁️',
    source: 'LinkedIn',
    tags: ['Workers', 'Rust', 'Distributed Systems'],
  },
  {
    id: 'app-009',
    company: 'Supabase',
    role: 'Developer Advocate',
    location: 'Remote (Global)',
    salary: '$120k – $160k',
    status: 'applied',
    appliedDate: daysAgo(3),
    lastActivity: daysAgo(3),
    requiresAction: false,
    logo: '⚡',
    source: 'Twitter/X',
    tags: ['PostgreSQL', 'Open Source', 'DevRel'],
  },
  {
    id: 'app-010',
    company: 'PlanetScale',
    role: 'Senior Engineer',
    location: 'Remote',
    salary: '$165k – $205k',
    status: 'rejected',
    appliedDate: daysAgo(35),
    lastActivity: daysAgo(14),
    requiresAction: false,
    logo: '🪐',
    source: 'Company Website',
    tags: ['MySQL', 'Vitess', 'Databases'],
  },
  {
    id: 'app-011',
    company: 'PostHog',
    role: 'Product Engineer (Growth)',
    location: 'Remote',
    salary: '$130k – $165k',
    status: 'applied',
    appliedDate: daysAgo(7),
    lastActivity: daysAgo(7),
    requiresAction: false,
    logo: '🦔',
    source: 'AngelList',
    tags: ['Analytics', 'Python', 'React'],
  },
  {
    id: 'app-012',
    company: 'Retool',
    role: 'Software Engineer II',
    location: 'San Francisco, CA',
    salary: '$155k – $195k',
    status: 'under_review',
    appliedDate: daysAgo(11),
    lastActivity: daysAgo(2),
    requiresAction: false,
    logo: '🔧',
    source: 'Greenhouse',
    tags: ['Low-code', 'React', 'SQL'],
  },
  {
    id: 'app-013',
    company: 'Deno',
    role: 'Runtime Engineer',
    location: 'Remote',
    salary: '$150k – $190k',
    status: 'shortlisted',
    appliedDate: daysAgo(28),
    lastActivity: daysAgo(6),
    requiresAction: false,
    logo: '🦕',
    source: 'Hacker News',
    tags: ['Rust', 'V8', 'WebAssembly'],
  },
  {
    id: 'app-014',
    company: 'Prisma',
    role: 'TypeScript Infrastructure Engineer',
    location: 'Remote (EU/US)',
    salary: '$140k – $180k',
    status: 'applied',
    appliedDate: daysAgo(2),
    lastActivity: daysAgo(2),
    requiresAction: false,
    logo: '🔷',
    source: 'LinkedIn',
    tags: ['TypeScript', 'ORM', 'Rust'],
  },
  {
    id: 'app-015',
    company: 'Railway',
    role: 'Platform Engineer',
    location: 'Remote',
    salary: '$135k – $170k',
    status: 'rejected',
    appliedDate: daysAgo(40),
    lastActivity: daysAgo(20),
    requiresAction: false,
    logo: '🚂',
    source: 'Twitter/X',
    tags: ['DevOps', 'Kubernetes', 'Go'],
  },
];

export const MOCK_VELOCITY_DATA: PipelineVelocityData[] = [
  { period: 'Week 1', interviews: 0, rejections: 1, shortlisted: 1 },
  { period: 'Week 2', interviews: 1, rejections: 2, shortlisted: 2 },
  { period: 'Week 3', interviews: 2, rejections: 3, shortlisted: 1 },
  { period: 'Week 4', interviews: 1, rejections: 1, shortlisted: 3 },
  { period: 'Week 5', interviews: 3, rejections: 2, shortlisted: 2 },
  { period: 'Week 6', interviews: 2, rejections: 1, shortlisted: 1 },
];

export const NEW_CARD_TEMPLATES: Omit<JobApplication, 'id' | 'appliedDate' | 'lastActivity'>[] = [
  {
    company: 'Anthropic',
    role: 'AI Safety Engineer',
    location: 'San Francisco, CA',
    salary: '$220k – $280k',
    status: 'under_review',
    requiresAction: false,
    logo: '🤖',
    source: 'Inbound Email',
    tags: ['AI', 'Safety', 'Python'],
  },
  {
    company: 'OpenAI',
    role: 'Research Engineer',
    location: 'Remote',
    salary: '$200k – $300k',
    status: 'interview_scheduled',
    requiresAction: true,
    schedulingLink: 'https://calendly.com/openai',
    logo: '✨',
    source: 'Inbound Email',
    tags: ['ML', 'Python', 'Research'],
  },
  {
    company: 'Arc Browser',
    role: 'Frontend Engineer',
    location: 'New York, NY',
    salary: '$160k – $200k',
    status: 'shortlisted',
    requiresAction: false,
    logo: '🌈',
    source: 'Inbound Email',
    tags: ['Swift', 'React', 'Design Systems'],
  },
  {
    company: 'Turso',
    role: 'Database Engineer',
    location: 'Remote',
    salary: '$130k – $170k',
    status: 'applied',
    requiresAction: false,
    logo: '🗄️',
    source: 'Inbound Email',
    tags: ['SQLite', 'Rust', 'libSQL'],
  },
];
